"""Create project table

Revision ID: 06fe87bc66c4
Revises: 01b2a513e8ea
Create Date: 2024-06-18 13:50:21.020954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fe87bc66c4'
down_revision = '01b2a513e8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectName', sa.String(length=100), nullable=False),
    sa.Column('clientIdentity', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('communicationLevel', sa.String(length=100), nullable=True),
    sa.Column('clientContactFirstName', sa.String(length=50), nullable=True),
    sa.Column('clientContactLastName', sa.String(length=50), nullable=True),
    sa.Column('clientContactJob', sa.String(length=100), nullable=True),
    sa.Column('clientContactEmail', sa.String(length=100), nullable=True),
    sa.Column('komodalProjectManagerFirstName', sa.String(length=50), nullable=True),
    sa.Column('useCase', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('startDate', sa.String(length=50), nullable=True),
    sa.Column('endDate', sa.String(length=50), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('platformUsed', sa.String(length=100), nullable=True),
    sa.Column('accountsCreated', sa.String(length=50), nullable=True),
    sa.Column('komodalSupportRating', sa.String(length=10), nullable=True),
    sa.Column('platformRating', sa.String(length=10), nullable=True),
    sa.Column('komodalPlatformRating', sa.String(length=10), nullable=True),
    sa.Column('komodalComment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
